language: generic
services:
  - docker
before_install:
  - docker build -t markiyan96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markiyan96/react-test npm test

after_success:
  - docker build -t markiyan96/multi-client ./client
  - docker build -t markiyan96/multi-nginx ./nginx
  - docker build -t markiyan96/multi-server ./server
  - docker build -t markiyan96/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push markiyan96/multi-client
  - docker push markiyan96/multi-nginx
  - docker push markiyan96/multi-server
  - docker push markiyan96/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-333127796530
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
